const char* wedding_day_name[] = {
    "Gruene Hochzeit",
    "Papierne Hochzeit",                    // 1
    "Baumwollene Hochzeit",
    "Lederne Hochzeit",
    "Seiden-hochzeit",
    "Hölzerne Hochzeit",
    "Zinnerne Hochzeit",
    "Kupferne Hochzeit",
    "Blecherne Hochzeit",
    "Keramik-hochzeit",
    "Rosen-hochzeit",                        // 10
    "Stahl-hochzeit",                       
    "Nickel-hochzeit",
    "Veichlchen-hochzeit",
    "Elfenbein-hochzeit",
    "Kristall-hochzeit",                     
    "Saphir-hochzeit",
    "Orchideen-hochzeit",
    "Türkis-hochzeit",
    "Perlmut-hochzeit",
    "Porzellan-hochzeit",                    // 20
    "Opal-hochzeit",
    "Bronze-hochzeit",
    "Titan-hochzeit",
    "Satin-hochzeit",
    "Silber-hochzeit",
    "Jade-hochzeit",
    "Mahagoni-hochzeit",
    "Nelken-hochzeit",
    "Samt-hochzeit",
    "Perlen-hochzeit",                       // 30
    "Linden-hochzeit",
    "Seifen-hochzeit",
    "Zinn-hochzeit",
    "Amber-hochzeit",
    "Leinen-hochzeit",
    "Smaragd-hochzeit",
    "Malachit-hochzeit",
    "Feuer-hochzeit",
    "Sonnen-hochzeit",
    "Rubin-hochzeit",                        // 40
    "Birken-hochzeit",
    "Granat-hochzeit",
    "Blei-hochzeit",
    "Sternen-hochzeit",
    "Messing-hochzeit",
    "Lavendel-hochzeit",
    "Kaschmir-hochzeit",
    "Diadem-hochzeit",
    "Zederne Hochzeit",
    "Goldene Hochzeit",                     // 50
    "Weiden-hochzeit",
    "Topas-hochzeit",
    "Uran-hochzeit",
    "Zeus-hochzeit",
    "Platin-hochzeit",
    "Astern-hochzeit",
    "Jade-hochzeit",
    "Engels-hochzeit",
    "Gezeiten-hochzeit",
    "Diamantene Hochzeit",                  // 60
    "Ulmen-hochzeit",
    "Aquamarin-hochzeit",
    "Quecksilber-hochzeit",
    "Himmels-hochzeit",
    "Eiserne Hochzeit",
    "Schnittlauch-hochzeit",
    "Steinerne Hochzeit",
    "Granit-hochzeit",
    "Laerchen-hochzeit",
    "Gnaden-hochzeit",                       // 70
    "Ocker-hochzeit",
    "Juwelen-hochzeit",
    "Gusseisen-hochzeit",
    "Apfel-hochzeit",
    "Kronjuwelen-hochzeit",
    "Zypressen-hochzeit",
    "Lavendel-hochzeit",
    "Ebenholz-hochzeit",
    "Kaffee-hochzeit",
    "Eichen-hochzeit",                       // 80
    "Kakao-hochzeit",
    "Nelken-hochzeit",
    "Begonien-hochzeit",
    "Chrysanthemen-hochzeit",
    "Engels-hochzeit",
    "Hortensien-hochzeit",
    "Walnuss-hochzeit",
    "Birnen-hochzeit",
    "Feigen-hochzeit",
    "Marmorne Hochzeit",                    // 90
    "Kiefern-hochzeit",
    "Lilien-hochzeit",
    "Lapislazuli-hochzeit",
    "Palmen-hochzeit",
    "Sandelholz-hochzeit",
    "Oliven-hochzeit",
    "Tannen-hochzeit",
    "Kiefern-hochzeit",
    "Weiden-hochzeit",
    "Himmels-hochzeit",                      // 100
};
